using AutoMapper;
using MinAPIMusicProject.Data;
using MinAPIMusicProject.DTOs;
using MinAPIMusicProject.Models;

namespace MinAPIMusicProject.Endpoints;

/*
 * Autogenerated playlist:
 * - rules
 * 
 */

public static class PlaylistEndpoints
{
    private static IEnumerable<PlaylistGenerator> _specialPlaylists;

    static PlaylistEndpoints()
    {
        _specialPlaylists = new PlaylistGenerator[]
        {
            new PlaylistGenerator().AddGenreRule(new []{"pop", "cerol", "jazz"})
                .AddDateRule(startDate: new DateTime(2024, 10, 1), endDate: new DateTime(2025, 1, 20))
                .SetLimit(30)
                .SetTitle("Christmas Playlist"),
            
        };
    }
    
    public static void AddPlaylistEndpoints(this IEndpointRouteBuilder app)
    {
        var endpoint = app.MapGroup("/api/playlists");

        endpoint.MapGet("/special", (MusicContext context, IMapper mapper) =>
        {
            var playlists = _specialPlaylists.First().Build(context);
            return Results.Ok(mapper.Map<IEnumerable<PlaylistDTO>>(new[]{playlists}));
        });
    }
}